#!/bin/bash

#
# This script will update the gh-pages branch with any changes that have been made to the steps
# and to the dependencies.
#
# The tutorial step changes are computed by checking out each step into a snapshot folder and then
# overwriting the step folders in gh-pages with these new ones.
# If there are any changes they will be committed
#
# The dependency changes are computed by running "bower update" then committing any changed files
# inside the bower_components folder onto the gh-pages branch.
#
# You should review these commits and push them to origin/gh-pages if valid.

# Exit on error and print each command as it is run
set -ex

ROOT_DIR=`dirname $0`/..
SNAP_DIR=reactjs-phonecat-snapshots-web

# Get into the correct directory
cd $ROOT_DIR

# Make sure we are on master
git checkout -f master


# Clean out the snapshot directory if it was left behind
rm -rf $SNAP_DIR
mkdir $SNAP_DIR

# Iterate through each step, checking it out and copying it into the temporary snapshot directory
for i in {0..12}
do
  mkdir $SNAP_DIR/step-$i
  git checkout -f step-$i

  gulp build

  cp -R dist/* $SNAP_DIR/step-$i/

  # In gh-pages the step directories are one directory further down so we must modify the path
  # to the bower_components in the index.html files.
  # node -e "require('shelljs/global'); sed('-i', /\\/phones\\/phones\\.json/, '/reactjs-phonecat/step-$i/phones/phones.json', '$SNAP_DIR/step-$i/assets/main.js');"
  # node -e "require('shelljs/global'); sed('-i', /phone.imageUrl/, '\"/reactjs-phonecat/step-$i\"+phone.imageUrl', '$SNAP_DIR/step-$i/assets/main.js');"

done


# Move the snapshot step folders into the gh-pages branch
git checkout -f gh-pages
rm -rf step-*
mv $SNAP_DIR/* .
rm -rf $SNAP_DIR

# Commit any changes to the steps
git add --all step-*
git add -u
git commit -m"chore(step): update live steps to new version of tutorial" || true


# Display an info message, including the last two commits
echo gh-pages has been updated. See the log below.
git log -2

# Push changes to the gh-pages branch on GitHub
git push origin gh-pages
